services:
  ollama:
    container_name: ollama
    image: docker.io/ollama/ollama:latest
    ports:
      - 11434:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    volumes:
      - ./ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  rag_service:
    build:
      context: .
      dockerfile: docker/Dockerfile.stt
    env_file:
      - .env-test
    command: sh -c "uvicorn app:app --host=0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    environment:
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_URL=6333
      - NUM_GPU_WORKERS=8
    depends_on:
      - qdrant
      - ollama
      - redis
      - celery
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s

  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile.bot
    command: python bot.py
    env_file:
      - .env-test
    depends_on:
      rag_service:
        condition: service_started

  qdrant:
    image: qdrant/qdrant:v1.15.1
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant/storage
    healthcheck:
      #test: curl --fail -s http://127.0.0.1:80/healthcheck || exit 1
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1
      interval: 30s
      timeout: 15s
      retries: 3

  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    command: celery -A redis_tasks.app worker --loglevel=info --concurrency=1
    environment:
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env-test
    depends_on:
      - qdrant
      - redis
      - ollama
    volumes:
      - ./whisper_model_cache:/home/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  redis:
    image: redis:7
